// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDtnmUPCU0ip5MDF4Uov4dWukxKDw_o5jM',
    appId: '1:1038388836082:web:128839a6e479a9317d026b',
    messagingSenderId: '1038388836082',
    projectId: 'chat-app-b5fbc',
    authDomain: 'chat-app-b5fbc.firebaseapp.com',
    storageBucket: 'chat-app-b5fbc.appspot.com',
    measurementId: 'G-QK1V5M7J35',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD2B4QmwrqsbiPwB9XC7U0zagsVVRNKdFA',
    appId: '1:1038388836082:android:a307edd34ddd21007d026b',
    messagingSenderId: '1038388836082',
    projectId: 'chat-app-b5fbc',
    storageBucket: 'chat-app-b5fbc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDQYfkqdFH_J2wP4S8W56_HMnUGiBhoVeI',
    appId: '1:1038388836082:ios:ce8aeabf9e6e2a367d026b',
    messagingSenderId: '1038388836082',
    projectId: 'chat-app-b5fbc',
    storageBucket: 'chat-app-b5fbc.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDQYfkqdFH_J2wP4S8W56_HMnUGiBhoVeI',
    appId: '1:1038388836082:ios:ce8aeabf9e6e2a367d026b',
    messagingSenderId: '1038388836082',
    projectId: 'chat-app-b5fbc',
    storageBucket: 'chat-app-b5fbc.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );
}
